#!/usr/bin/env python3
"""Profile tasks passed as a CSV (generated by the iteration report) or via json-lines input.

Usage:
  python3 scripts/profile_tasks.py <csv_file> [--overrides overrides.json]

Outputs profiled tasks as JSON to stdout.
"""
import sys
from pathlib import Path
import csv
import json
from utilities.task_profiler import profile_tasks


def load_tasks_from_csv(p: Path):
    with p.open("r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        return [r for r in reader]


def main(argv):
    if len(argv) < 2:
        print(__doc__)
        return 2
    p = Path(argv[1])
    if not p.exists():
        print("file not found", p)
        return 2
    overrides = None
    if len(argv) >= 4 and argv[2] == "--overrides":
        overrides = argv[3]
    tasks = load_tasks_from_csv(p)
    profiled = profile_tasks(tasks, overrides)
    print(json.dumps(profiled, indent=2))
    return 0

if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
